### ISSUE TITLE
Better AA

### ISSUE THREAD

**Issue by SuperSlimek** [Terri00/CS-GO-Auto-Radar#10]
Hi, any chance for better AA in the future? 4x, 8x?

**Comment by Terri00** [comment]
that should be an easy add. any specific cases 2x doesn't work well enough? maybe if the map is so big, a higher resolution might work better anyway

**Comment by SuperSlimek** [comment]
Small details and edges on props are still very pixelated so they should be smoothed out, this isn't really an issue in game but it does bother me when looking at the radar in full size. Is the higher resolution thing something we can already do with the current build or does it have to be implemented?
My example
![1721338314_preview_de_bregov_v2_b5_radar_ws](https://user-images.githubusercontent.com/14257834/58149405-1bb58c00-7c63-11e9-8c53-1230fe9b975f.png)

**Comment by Terri00** [comment]
Yeah I see what you mean now. I'll take a look at that. For the higher resolution you should be able to specify for example: `-w 2048 -h 2048` in the command line arguments when you compile it.

**Comment by Terri00** [comment]
eb8326d31c8748e7658ab6c5e5435a4dd57eebab adds 4x MSAA, 8x MSAA and FXAA.
Modes will be available in the next release, recommended mode: FXAA.
