### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by exedys** [Terri00/CS-GO-Auto-Radar#12]
-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive/bin/tar"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive/bin/tar/AutoRadar.exe" -g "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo" "c:\users\millo\desktop\csgo\maps\current projects\standard maps\de_sovereign\files\vmf/de_sovereign"
-------------------------------------------------------------------------------

(required: min core 3.3.0) opengl version: 3.3.0 NVIDIA 397.64
KV Read time: 0ms
C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/../
Version: 2
TreeSize: 10898937
   *.svg
   *.vsc
   *.raw
   *.txt
   *.mp3
   *.wav
   *.png
   *.res
   *.ani
   *.phz
   *.phy
   *.vmt
   *.pcf
   *.vtf
   *.vtx
   *.vvd
   *.mdl
   *.
Done reading
88934 entries read
Finished setting up filesystem.
vmf [c:/users/millo/desktop/csgo/maps/current projects/standard maps/de_sovereign/files/vmf/de_sovereign.vmf] Opening
vmf [c:/users/millo/desktop/csgo/maps/current projects/standard maps/de_sovereign/files/vmf/de_sovereign.vmf] Processing VMF data
KV Read time: 1181ms
vmf [c:/users/millo/desktop/csgo/maps/current projects/standard maps/de_sovereign/files/vmf/de_sovereign.vmf] Processing visgroups
'Details': 18
'tar_layout': 22
'tar_mask': 23
'tar_cover': 24
vmf [location/de_sovereign.vmf] Processing solids
vmf [location/de_sovereign.vmf] Processing entities
vmf [location/de_sovereign.vmf] Done!
vmf [location/de_sovereign.vmf] Failed to load resource: error

vmf [location/de_sovereign.vmf] Failed to load resource: error

Loading texture: textures/gradients/gradientmap_2.png
Loading texture: textures/grid.png
Bounds MAXY: -96
Bounds MINY: -516
-4364,-96,5013
873,-516,1733
Compiling shader from source: shaders/gBuffer.vs
Compiling shader from source: shaders/gBuffer.fs
Compiling shader from source: shaders/gBuffer.vs
Compiling shader from source: shaders/iBuffer.fs
Compiling shader from source: shaders/fullscreenbase.vs
Compiling shader from source: shaders/fullscreenbase.fs
Compiling shader from source: shaders/fullscreenbase.vs
Compiling shader from source: shaders/ss_comp_multilayer_blend.fs
Compiling shader from source: shaders/fullscreenbase.vs
Compiling shader from source: shaders/ss_comp_multilayer_finalstage.fs
Compiling shader from source: shaders/fullscreenbase.vs
Compiling shader from source: shaders/ss_fxaa.fs
Compiling shader from source: shaders/fullscreenbase.vs
Compiling shader from source: shaders/ss_msaa.fs
Loading texture: textures/modulate.png
v10000
^-10000

**Comment by Terri00** [comment]
Hey, looks like an issue with model loading.

Try this build, it shouldn't crash when some kind of missing models are present:
[AutoRadar_2.5.0b#12-installbundle.zip](https://github.com/Terri00/CS-GO-Auto-Radar/files/3327041/AutoRadar_2.5.0b.12-installbundle.zip)

Please send me the vmf (discord Terri00#1024) so I can track down why the model is getting skipped in the first place. Cheers :)
