### ISSUE TITLE
Props cannot be used as tar_mask

### ISSUE THREAD

**Issue by 18swenskiq** [Terri00/CS-GO-Auto-Radar#13]
Currently, only brushes can be used to mask.

**Comment by Terri00** [comment]
Types of: `prop_static` `func_detail` and world brushes work as part of any visgroup.
Make sure what you want to use as a mask, is **ONLY** in your mask visgroup.

![image](https://user-images.githubusercontent.com/15938911/60385772-2bf03080-9a85-11e9-9ee8-20bb8338a225.png)

If this doesn't solve your issue I will need to see the vmf. Closed for now.
