### ISSUE TITLE
Shadows Option Not Working - AutoRadar_2.5.0b

### ISSUE THREAD

**Issue by tophattwaffle** [Terri00/CS-GO-Auto-Radar#16]
When using the Shadows feature, no shadows are produced in radar image.

See attached image for the tar_config settings, and the resulting radar.

![image](https://user-images.githubusercontent.com/6774125/62408865-ca941380-b594-11e9-9222-57973803a78f.png)

Output from compile.

> -------------------------------------------------------------------------------
> Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive/bin/tar"
> -------------------------------------------------------------------------------
> 
> 
> -------------------------------------------------------------------------------
> Running command: "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive/bin/tar/AutoRadar.exe" -g "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo" "e:\dropbox\tutorials\maps/tutorial_27"
> -------------------------------------------------------------------------------
> 
> (required: min core 3.3.0) opengl version: 3.3.0 NVIDIA 419.67
> KV Read time: 0ms
> C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/../
> Version: 2
> TreeSize: 10902439
>    *.svg
>    *.vsc
>    *.raw
>    *.txt
>    *.mp3
>    *.wav
>    *.png
>    *.res
>    *.ani
>    *.phz
>    *.phy
>    *.vmt
>    *.pcf
>    *.vtf
>    *.vtx
>    *.vvd
>    *.mdl
>    *.
> Done reading
> 89011 entries read
> Finished setting up filesystem.
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Opening
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Processing VMF data
> KV Read time: 599ms
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Processing visgroups
> 'tar_layout': 14
> 'tar_cover': 15
> 'tar_mask': 16
> 'tar_overlap': 19
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Processing solids
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Processing entities
> vmf [e:/dropbox/tutorials/maps/tutorial_27.vmf] Done!
> Loading texture: textures/gradients/gradientmap_0.png
> Loading texture: textures/grid.png
> Bounds MAXY: 288
> Bounds MINY: -192
> -2560,288,3809
> 2732,-192,-1152
> Compiling shader from source: shaders/gBuffer.vs
> Compiling shader from source: shaders/gBuffer.fs
> Compiling shader from source: shaders/gBuffer.vs
> Compiling shader from source: shaders/iBuffer.fs
> Compiling shader from source: shaders/fullscreenbase.vs
> Compiling shader from source: shaders/fullscreenbase.fs
> Compiling shader from source: shaders/fullscreenbase.vs
> Compiling shader from source: shaders/ss_comp_multilayer_blend.fs
> Compiling shader from source: shaders/fullscreenbase.vs
> Compiling shader from source: shaders/ss_comp_multilayer_finalstage.fs
> Compiling shader from source: shaders/fullscreenbase.vs
> Compiling shader from source: shaders/ss_fxaa.fs
> Compiling shader from source: shaders/fullscreenbase.vs
> Compiling shader from source: shaders/ss_msaa.fs
> Loading texture: textures/modulate.png
> v10000
> ^-10000
> Finished. Press a key to close.

**Comment by Terri00** [comment]
Shadows in got missed in the 2.5 rewrite unfortunately. Will be back in next version.

**Comment by tophattwaffle** [comment]
Makes sense! Love the project, awesome work. Will close the issue since it isn't actually an issue.
