### ISSUE TITLE
I can't open cs go sdk

### ISSUE THREAD

**Issue by BAdemon555** [Terri00/CS-GO-Auto-Radar#35]
So I download auto radar but I didn't entered the commands, and now i cant't open sdk.
Please help!

**Comment by Terri00** [comment]
Verify integrity of sdk files through steam

**Comment by BAdemon555** [comment]
Verify integrity dint work but i keep getting GameConfig.txt is missing

**Comment by BAdemon555** [comment]
Okey i got it forking
